[package]
name = "queryer_py" 
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"] 

[dependencies]
queryer = { path = "../queryer" } 
tokio = { version = "1", features = ["full"] }
pyo3 = { version = "0.22.2", features = ["extension-module"] }
